build:
  quality:
    image: ensime/ensime:v1.x-cache
    pull: true
    commands:
      - pip install --upgrade virtualenv
      - make lint
      - make format ;
        if $(! git diff --exit-code --quiet) ; then
          echo "Code formatting does not meet the project's standards:" ;
          git --no-pager diff ;
          exit 1 ;
        fi

  test:
    image: ensime/ensime:v1.x-cache
    commands:
      - pip install --upgrade virtualenv
      - make test
    when:
      success: true
